language: python
python:
  - "3.5"
env:
  - GITHUB_TOKEN="1fefaa93eaf6816640dc14e14fcbbc0f00914516"
install:
  - "pip install ."
script: 
  - "octohatrack LABHR/octohatrack"
  - "python octohatrack.py LABHR/octohatrack-rb --no-cache"
  - "python octohatrack.py programminghistorian/jekyll -w"
