language: python
python:
  - "3.4"
env:
  - GITHUB_TOKEN="1fefaa93eaf6816640dc14e14fcbbc0f00914516"
install:
  - "pip install ."
script: 
  - "DEBUG=true octohat glasnt/octohat-rb"
  - "python3 octohat.py glasnt/octohat -c -g -n"
  - "cat glasnt_octohat_contrib.html"
